### ISSUE TITLE
Web user event processing is not done in the main thread

### ISSUE THREAD

**Issue by Gleethos** [Gleethos/Tribalism#10]
Currently web users can not login or register because the user events are processed by the
web-server thread instead of the (main) application/backend thread, which is what the database expects!
Thankfully the little ORM I built fo our project threw this exception:
```
Caused by: java.lang.RuntimeException: No connection found for thread 'qtp1813187653-45'!
	at dal.impl.AbstractDataBase._getConnection(AbstractDataBase.java:80)
	at dal.impl.AbstractDataBase._newPreparedStatement(AbstractDataBase.java:166)
	at dal.impl.AbstractDataBase._for(AbstractDataBase.java:186)
	at dal.impl.AbstractDataBase._query(AbstractDataBase.java:238)
	at dal.impl.SQLiteDataBase$2.asList(SQLiteDataBase.java:514)
	at app.AppContext.userExists(AppContext.java:39)
	at app.LoginViewModel.login(LoginViewModel.java:70)
	... 38 more
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.BindingUtil.callViewModelMethod(BindingUtil.java:217)
	at net.BindingWebSocket.callMethodOnVM(BindingWebSocket.java:168)
	at net.BindingWebSocket.onMessage(BindingWebSocket.java:90)
```
...which it does because it is built to be thread-safe! 🥇 

So to fix this I will have to delegate the VM call requests the server thread gets from the web user
to a main thread event queue.

**Comment by Gleethos** [comment]
fixed in #11
